---
- hosts: master
  become: true
  roles:
    - ufw-role
  vars:
    ufw_rules:
      - rule: allow
        to_port: 22
        protocol: tcp
        comment: 'allow incoming connection on 22'
      - rule: allow
        to_port: 179
        protocol: tcp
        comment: 'allow incoming connection on 179'
      - rule: allow
        to_port: 443
        protocol: tcp
        comment: 'allow incoming connection on 443'
      - rule: allow
        to_port: 2379
        protocol: tcp
        comment: 'allow incoming connection on 2379'
      - rule: allow
        to_port: 2380
        protocol: tcp
        comment: 'allow incoming connection on 2380'
      - rule: allow
        to_port: 4149
        protocol: tcp
        comment: 'allow incoming connection on 4149'
      - rule: allow
        to_port: 4789
        protocol: udp
        comment: 'allow incoming connection on 4789'
      - rule: allow
        to_port: 5473
        protocol: tcp
        comment: 'allow incoming connection on 5473'
      - rule: allow
        to_port: 6443
        protocol: tcp
        comment: 'allow incoming connection on 6443'
      - rule: allow
        to_port: 9099
        protocol: tcp
        comment: 'allow incoming connection on 9099'
      - rule: allow
        to_port: 10250
        protocol: tcp
        comment: 'allow incoming connection on 10250'
      - rule: allow
        to_port: 10251
        protocol: tcp
        comment: 'allow incoming connection on 10251'
      - rule: allow
        to_port: 10252
        protocol: tcp
        comment: 'allow incoming connection on 10252'
      - rule: allow
        to_port: 10255
        protocol: tcp
        comment: 'allow incoming connection on 10255'
      - rule: allow
        to_port: 10256
        protocol: tcp
        comment: 'allow incoming connection on 10256'
      - rule: allow
        to_port: 36000
        protocol: tcp
        comment: 'allow incoming connection on 36000'
      - rule: allow
        to_port: 36001
        protocol: tcp
        comment: 'allow incoming connection on 36001'
      - rule: allow
        to_port: 36002
        protocol: tcp
        comment: 'allow incoming connection on 36002'
      - rule: allow
        to_port: 36003
        protocol: tcp
        comment: 'allow incoming connection on 36003'
      - rule: allow
        to_port: 36004
        protocol: tcp
        comment: 'allow incoming connection on 36004'
      - rule: allow
        to_port: 36005
        protocol: tcp
        comment: 'allow incoming connection on 36005'
      - rule: allow
        to_port: 36006
        protocol: tcp
        comment: 'allow incoming connection on 36006'
      - rule: allow
        to_port: 36007
        protocol: tcp
        comment: 'allow incoming connection on 36007'
      - rule: allow
        to_port: 36008
        protocol: tcp
        comment: 'allow incoming connection on 36008'
      - rule: allow
        to_port: 36009
        protocol: tcp
        comment: 'allow incoming connection on 36009'
      - rule: allow
        to_port: 36010
        protocol: tcp
        comment: 'allow incoming connection on 36010'
      - rule: allow
        to_port: 36011
        protocol: tcp
        comment: 'allow incoming connection on 36011'
      - rule: allow
        to_port: 36012
        protocol: tcp
        comment: 'allow incoming connection on 36012'
      - rule: allow
        to_port: 36013
        protocol: tcp
        comment: 'allow incoming connection on 36013'
      - rule: allow
        to_port: 36014
        protocol: tcp
        comment: 'allow incoming connection on 36014'
      - rule: allow
        to_port: 36015
        protocol: tcp
        comment: 'allow incoming connection on 36015'
      - rule: allow
        to_port: 36016
        protocol: tcp
        comment: 'allow incoming connection on 36016'
      - rule: allow
        to_port: 36017
        protocol: tcp
        comment: 'allow incoming connection on 36017'
      - rule: allow
        to_port: 360018
        protocol: tcp
        comment: 'allow incoming connection on 36018'
      - rule: allow
        to_port: 36019
        protocol: tcp
        comment: 'allow incoming connection on 36019'
      - rule: allow
        to_port: 36020
        protocol: tcp
        comment: 'allow incoming connection on 36020'


- hosts: "master"
  become_method: sudo
  become: yes
  gather_facts: yes
  tasks:
    - name: Initialize the Kubernetes cluster using kubeadm
      command: kubeadm init --apiserver-advertise-address="192.168.122.101" --apiserver-cert-extra-sans="192.168.122.101"  --node-name master --pod-network-cidr=10.100.0.0/16

    - name: Restart kubelet
      service:
        name: kubelet
        daemon_reload: yes
        state: restarted


    - name: create .kube directory
      become: yes
      file:
        path: /home/vmadmin/.kube
        state: directory
        mode: 0755


    - name: copies admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vmadmin/.kube/config
        remote_src: yes
        owner: vmadmin

    - name: install Pod network
      become: yes
      become_user: vmadmin
      command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
      args:
        chdir: /home/vmadmin

    - name: Get the token for joining the worker nodes
      become: yes
      shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command

    - name: Copy join command to local file.
      become: yes
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777
